version: '3'

services:
  nestjs-mysql-db:
    image: mysql:8.0
    container_name: teachteam-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: goer-admin
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_ROOT_HOST: '%'